// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiI7er3ZT1w65TWvaVu-9_e-VlxLVK8k',
    appId: '1:750935514151:web:64aefa2a868dc2631f4202',
    messagingSenderId: '750935514151',
    projectId: 'crud-flutter-firebase-94cc5',
    authDomain: 'crud-flutter-firebase-94cc5.firebaseapp.com',
    storageBucket: 'crud-flutter-firebase-94cc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNILp4oHHoZqp0xiadF5eyCyZm_jWDIg',
    appId: '1:750935514151:android:33c4d8872b1a0fe11f4202',
    messagingSenderId: '750935514151',
    projectId: 'crud-flutter-firebase-94cc5',
    storageBucket: 'crud-flutter-firebase-94cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKm8ZUQN0AvGbCq-Ru_CnTAcv_5S18BZA',
    appId: '1:750935514151:ios:b6c9976a87184b0a1f4202',
    messagingSenderId: '750935514151',
    projectId: 'crud-flutter-firebase-94cc5',
    storageBucket: 'crud-flutter-firebase-94cc5.appspot.com',
    iosClientId: '750935514151-5mbinjdgn1eu3qgaif827lvfk22sac9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKm8ZUQN0AvGbCq-Ru_CnTAcv_5S18BZA',
    appId: '1:750935514151:ios:b6c9976a87184b0a1f4202',
    messagingSenderId: '750935514151',
    projectId: 'crud-flutter-firebase-94cc5',
    storageBucket: 'crud-flutter-firebase-94cc5.appspot.com',
    iosClientId: '750935514151-5mbinjdgn1eu3qgaif827lvfk22sac9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCrud',
  );
}
